### ISSUE TITLE
Is there a way/ method of creating tables using models

### ISSUE THREAD

**Issue by Arap-Odawa** [Intreecom/scyllapy#42]
Dear @s3rius , and Intreecom team,

How do I utilise a models based method to create tables while using scyllapy, ie convert the following (snip1) into a model-based statement that can create tables as detailed in snip 2:

Snip 1:

```
from scyllapy import Scylla
from scyllapy.query_builder import Insert, Select, Update, Delete


async def main(scylla: Scylla):
    await scylla.execute("CREATE TABLE users(id INT PRIMARY KEY, name TEXT)")
```

Snip 2:

```
from uuid import UUID

from cassandra.cqlengine import columns
from cassandra.cqlengine.models import Model

class Task(Model):
    __table_name__ = "tasks"
    __keyspace__ = "todo_keyspace"

    id = columns.UUID(primary_key=True)
    title = columns.Text(min_length=3, max_length=255)
    description = columns.Text(min_length=0, max_length=512)
    is_completed = columns.Boolean(default=False)
```

Thanks for your support.

Regards,

Odawa

**Comment by caniko** [comment]
You can't, this is not supported. Make your tables with the datastax driver, and then use scyllapy for interaction.

**Comment by Arap-Odawa** [comment]
Thanks @caniko for your response.

It seems that the scyllapy was created for use by developers who have tables that have very few variables (less than 15 or 20) since it is not easy to define the columns if they are more than 10 a situation that would really benefit from the models-based table declaration since you'd only declare them once and re-use them.

How would you go about describing a table with more than 20 columns, can escape work for the declaration, something like the code snippett below?

```
async def main(scylla: Scylla):
    await scylla.execute("CREATE TABLE users(id INT PRIMARY KEY, name TEXT, uuid1 UUID, uuid2 UUID, uuid3 UUID......
   uuidn UUID )")
```

Moving to the next line kind of breaks the CREATE TABLE string

**Comment by Arap-Odawa** [comment]
Solved this. Used the triple quotes.
