### ISSUE TITLE
scyllapy.exceptions.ScyllaPyBindingError: Binding error. Cause: Unsupported type for parameter binding: "Decimal".

### ISSUE THREAD

**Issue by Arap-Odawa** [Intreecom/scyllapy#44]
This is a problem that even ChatGPT4 and Google are unable to provide a solution to. Is there a workaround for this? @s3rius , @tschiolborg 

https://www.google.com/search?q=scyllapy.exceptions.ScyllaPyBindingError%3A+Binding+error.+Cause%3A+Unsupported+type+for+parameter+binding%3A+%22Decimal%22.&rlz=1C1GCEU_enKE1034KE1034&oq=scyllapy.exceptions.ScyllaPyBindingError%3A+Binding+error.+Cause%3A+Unsupported+type+for+parameter+binding%3A+%22Decimal%22.&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDE3NzJqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8

[](url)

**Comment by s3rius** [comment]
This issue is fixed by #46. Will be released soon.

**Comment by Arap-Odawa** [comment]
Thanks @s3rius , this is very much appreciated. I hope that soon is soon, despite your very busy schedules.

Thanks much,

Odawa

**Comment by Arap-Odawa** [comment]
Hi @s3rius , @tschiolborg  and Intreecom Team, I hope that you're all keeping well.

 I noticed that the last time any major changes were made to this module was 3 weeks ago. I've been checing regularly for the releases since I'm not very familiar with deploying modules directly from Github code (I know it's possible, I'll learn that as time goes by), but, it definitely much easier to just deploy from modules so that it is easier to manage the updates in future.

Big Q: How much longer do we have to wait to use the enhanced version of this module to be released? We are your eager fans and are waiting to use the extended capabilities in our applications.


Thanks,

Regards,

Odawa

**Comment by s3rius** [comment]
Sorry for the inconvenience. I thought that the code was released. I've created a new release now. Thanks for noticing.

**Comment by Arap-Odawa** [comment]
Thanks @s3rius  for the prompt action. Does the release also automatically  update in the https://pypi.org/project/scyllapy/ website? It is still reading 1.3.0 which was released in November, 2023.

Thanks,

Odawa

**Comment by Arap-Odawa** [comment]
> Thanks @s3rius for the prompt action. Does the release also automatically update in the https://pypi.org/project/scyllapy/ website? It is still reading 1.3.0 which was released in November, 2023.
> 
> Thanks,
> 
> Odawa

This has reflected in the https://pypi.org/project/scyllapy/ site. 


Many thanks for the tremendous work you guys are doing.

Thanks,

Odawa
